spring:
  application:
    name: book-app-backend
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234